### ISSUE TITLE
Bug: The permit typehashes need to be ordered alphabetically

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/relayer#23]
This ones a constant struggle with working with EIP721 hashed data. Potentially longer term idea is to write a library to help construct typehashes properly.

And even longer term is to hopefully have cheatcodes in foundry to test that these are constructed with the correct EIP712 construction.

**Comment by zhongeric** [comment]
This is fixed in latest main although would be nice to explore a longer term solution in the future, closing for now
