### ISSUE TITLE
gas opt- might save gas to precompute these then use them in the comparisons above @zhongeric

### ISSUE THREAD

**Issue by willpote** [Uniswap/relayer#72]
```
            // TODO gas opt- might save gas to precompute these then use them in the comparisons above @zhongeric
```

https://github.com/Uniswap/relayer/blob/bd7f76e259e7b222976d02c0cfb78b4a62837e79/src/lib/FeeEscalatorLib.sol#L32

**Comment by zhongeric** [comment]
it's not clear which fields can be precomputed without the conditional logic before it
