### ISSUE TITLE
Nit: Use consistent punctuation (capitals/periods) in comments. 

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/relayer#73]
```
// TODO: Nit: Use consistent punctuation (capitals/periods) in comments. @zhongeric
```

https://github.com/Uniswap/relayer/blob/bd7f76e259e7b222976d02c0cfb78b4a62837e79/src/interfaces/IMulticall.sol#L4

**Comment by zhongeric** [comment]
can you take this with test renaming? @snreynolds
